# Ngrok tunnel only (port 5173). Requires Vite already running.
# Called by start-ngrok.ps1 — or run manually after npm run dev.
# Usage: .\scripts\start-ngrok-tunnel.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root
. (Join-Path $PSScriptRoot "_managix-common.ps1")

$envFile = Join-Path $Root "ngrok.local.env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+)=(.*)$') {
            [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
        }
    }
}

$ngrok = Get-Command ngrok -ErrorAction SilentlyContinue
if (-not $ngrok) {
    Write-Host "ERROR: ngrok not found. Install: winget install ngrok.ngrok" -ForegroundColor Red
    exit 1
}

Get-Process -Name ngrok -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1

$viteUp = $false
foreach ($addr in @("127.0.0.1", "localhost")) {
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect($addr, 5173)
        $tcp.Close()
        $viteUp = $true
        break
    }
    catch { }
}
if (-not $viteUp) {
    Write-Host "ERROR: Nothing is listening on port 5173." -ForegroundColor Red
    Write-Host "Start frontend first:  .\scripts\start-local.ps1" -ForegroundColor Yellow
    exit 1
}

$logFile = Join-Path $Root "ngrok.log"
$errFile = Join-Path $Root "ngrok.err.log"
Remove-Item $logFile, $errFile -Force -ErrorAction SilentlyContinue

$ngrokArgs = @("http", "127.0.0.1:5173", "--log=stdout", "--log-format=logfmt", "--log-level=info")
$proc = Start-Process -FilePath "ngrok" -ArgumentList $ngrokArgs -PassThru `
    -RedirectStandardOutput $logFile -RedirectStandardError $errFile -WindowStyle Hidden

$publicUrl = $null
$deadline = (Get-Date).AddSeconds(25)
while ((Get-Date) -lt $deadline) {
    Start-Sleep -Seconds 1
    if ($proc.HasExited) {
        Write-Host "ERROR: ngrok exited early. Log:" -ForegroundColor Red
        if (Test-Path $logFile) { Get-Content $logFile -Tail 20 }
        if (Test-Path $errFile) { Get-Content $errFile -Tail 10 }
        exit 1
    }
    try {
        $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -Method Get -TimeoutSec 2
        $publicUrl = ($tunnels.tunnels | Select-Object -First 1).public_url
        if ($publicUrl) { break }
    }
    catch { }
}

if (-not $publicUrl) {
    Write-Host "ERROR: Could not read tunnel URL from http://127.0.0.1:4040" -ForegroundColor Red
    if (Test-Path $logFile) { Get-Content $logFile -Tail 20 }
    exit 1
}

$frontendDir = Resolve-FrontendDir $Root
$envDev = Join-Path $frontendDir ".env.development.local"
$envContent = @"
# Auto-generated by start-ngrok-tunnel.ps1 - use same-origin /api via Vite proxy
VITE_API_BASE_URL=/api
"@
Set-Content -Path $envDev -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "SUCCESS" -ForegroundColor Green
Write-Host "Share this URL:" -ForegroundColor Green
Write-Host "  $publicUrl" -ForegroundColor White
Write-Host "API (proxied):  $publicUrl/api" -ForegroundColor Cyan
Write-Host "Dashboard:      http://127.0.0.1:4040" -ForegroundColor Cyan
Write-Host "Updated: $envDev" -ForegroundColor Gray
Write-Host "Restart Vite if it was already running before this script." -ForegroundColor Yellow
