# Ngrok deployment for MANAGIX
# Run from repo root:  .\scripts\start-ngrok.ps1
#
# Uses ONE tunnel (ngrok free tier) on port 5173.
# Vite proxies /api -> localhost:7005 so remote users hit backend through the same URL.
# AI services (8000-8002) stay local; the Functions host calls them on 127.0.0.1.

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

# Load token (also stored via: ngrok config add-authtoken)
$envFile = Join-Path $Root "ngrok.local.env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+)=(.*)$') {
            [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
        }
    }
}

$ngrok = Get-Command ngrok -ErrorAction SilentlyContinue
if (-not $ngrok) {
    Write-Host "ERROR: ngrok not found. Install: winget install ngrok.ngrok" -ForegroundColor Red
    exit 1
}

# Stop stale ngrok so port 4040 is free
Get-Process -Name ngrok -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1

Write-Host ""
Write-Host "=== MANAGIX Ngrok ===" -ForegroundColor Cyan
Write-Host "Required locally (before sharing the ngrok URL):" -ForegroundColor Yellow
Write-Host "  1. Backend:     func start  in MANAGIX_BACKEND\MANAGIX_FYP_2025  (port 7005)"
Write-Host "  2. Frontend:    npm run dev  in MANAGIX_FRONTEND\managix         (port 5173)"
Write-Host "  3. AI services: .\scripts\start-ai-services.ps1  (ports 8000-8002)"
Write-Host ""
Write-Host "Open the ROOT URL in your browser (no /api at the end):" -ForegroundColor Yellow
Write-Host "  First visit: click 'Visit Site' on the ngrok warning page if shown." -ForegroundColor Yellow
Write-Host ""

# Single tunnel - works on ngrok v3 free plan
$logFile = Join-Path $Root "ngrok.log"
$errFile = Join-Path $Root "ngrok.err.log"
Remove-Item $logFile, $errFile -Force -ErrorAction SilentlyContinue

# Verify Vite is listening before starting ngrok (avoids ERR_NGROK_8012)
$viteUp = $false
foreach ($addr in @("127.0.0.1", "localhost")) {
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect($addr, 5173)
        $tcp.Close()
        $viteUp = $true
        break
    }
    catch { }
}
if (-not $viteUp) {
    Write-Host "ERROR: Nothing is listening on port 5173." -ForegroundColor Red
    Write-Host "Start Vite first:  cd MANAGIX_FRONTEND\managix  &&  npm run dev" -ForegroundColor Yellow
    exit 1
}

# Use 127.0.0.1 explicitly — ngrok defaults to [::1] on Windows which Vite may not bind
$ngrokArgs = @("http", "127.0.0.1:5173", "--log=stdout", "--log-format=logfmt", "--log-level=info")
$proc = Start-Process -FilePath "ngrok" -ArgumentList $ngrokArgs -PassThru `
    -RedirectStandardOutput $logFile -RedirectStandardError $errFile -WindowStyle Hidden

$publicUrl = $null
$deadline = (Get-Date).AddSeconds(25)
while ((Get-Date) -lt $deadline) {
    Start-Sleep -Seconds 1
    if ($proc.HasExited) {
        Write-Host "ERROR: ngrok exited early. Log:" -ForegroundColor Red
        if (Test-Path $logFile) { Get-Content $logFile -Tail 20 }
        if (Test-Path $errFile) { Get-Content $errFile -Tail 10 }
        exit 1
    }
    try {
        $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -Method Get -TimeoutSec 2
        $publicUrl = ($tunnels.tunnels | Select-Object -First 1).public_url
        if ($publicUrl) { break }
    }
    catch {
        # API not ready yet
    }
}

if (-not $publicUrl) {
    Write-Host "ERROR: Could not read tunnel URL from http://127.0.0.1:4040" -ForegroundColor Red
    if (Test-Path $logFile) { Get-Content $logFile -Tail 20 }
    if (Test-Path $errFile) { Get-Content $errFile -Tail 10 }
    exit 1
}

$envDev = Join-Path $Root "MANAGIX_FRONTEND\managix\.env.development.local"
$envContent = @"
# Auto-generated by start-ngrok.ps1 - use same-origin /api via Vite proxy
VITE_API_BASE_URL=/api
"@
Set-Content -Path $envDev -Value $envContent -Encoding UTF8

Write-Host "SUCCESS" -ForegroundColor Green
Write-Host ""
Write-Host "Share this URL with your team:" -ForegroundColor Green
Write-Host "  $publicUrl" -ForegroundColor White
Write-Host ""
Write-Host "API (proxied through Vite):  $publicUrl/api" -ForegroundColor Cyan
Write-Host "Ngrok dashboard:             http://127.0.0.1:4040" -ForegroundColor Cyan
Write-Host "Updated: $envDev" -ForegroundColor Gray
Write-Host ""
Write-Host "IMPORTANT:" -ForegroundColor Yellow
Write-Host "  - Keep the 'npm run dev' terminal OPEN. If Vite stops, ngrok shows ERR_NGROK_8012." -ForegroundColor Yellow
Write-Host "  - If that happens: restart Vite, then run  .\scripts\restart-ngrok.ps1" -ForegroundColor Yellow
Write-Host "  - Restart Vite after this script if .env.development.local changed." -ForegroundColor Yellow
Write-Host "Stop ngrok:  Stop-Process -Name ngrok -Force" -ForegroundColor Gray
